version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-world-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w6mjh6hnu0y5"
s3_prefix = "sam-hello-world-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
